FROM php:7.1-apache
RUN apt-get update && apt-get install -y  git zip  \
                libfreetype6-dev \
                libjpeg62-turbo-dev \
                libmcrypt-dev \
                libpng-dev \
        && docker-php-ext-install -j$(nproc) iconv mcrypt \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd

#RUN curl --silent --show-error https://getcomposer.org/installer | php
#RUN mv composer.phar /usr/local/bin/composer

COPY ./app  /var/www/html/app

WORKDIR /var/www/html/app
